server:
  port: 3306
spring:
  thymeleaf:
    cache: false
  datasource:
    password: Masafumi9@
    url: jdbc:mysql://localhost:3306/studyabroad
    username: root
  mail:
    host: smtp.gmail.com
    port: 587
    username:  morimamama123@gmail.com #gmailアドレス
    password: rmbuwqwrujpjdrfi #Googleのアプリパスワード
    propeties.mail.smtp.auth: true
    properties.mail.smtp.starttls.enable: true
    properties.mail.smtp.trust: smtp.google.com

mybatis:
  configuration:
    mapUnderscoreToCamelCase: true
  mapper-locations:
        - classpath*:/com/masafumi/studyabroad/model/mapper/**/*.xml

logging:
  level:
    org:
      springframework: WARN
    com.masafumimori.studyabroad.model.mapper: DEBUG